# tests/macro/test_deep_research_handoff.py
"""
Unit tests for the Deep Research → Macro Analyst handoff layer.

Tests parse_synthesis_document (tools/deep_research.py) — the function that
validates Deep Research output before handing it to the Macro Analyst.

No main.py import, no API credentials, no network access required.
Mark: pytest (default — runs without -m integration flag)
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent.parent))

from tools.deep_research import parse_synthesis_document

# ── Fixtures ──────────────────────────────────────────────────────────────────

_FIXTURE_DIR = pathlib.Path(__file__).parent / "fixtures"


def _valid_doc() -> str:
    return (_FIXTURE_DIR / "synthesis_document_valid.txt").read_text()


def _build_doc(sections: list[str], sources_added: int = 3) -> str:
    """Build a minimal synthesis document with specified sections and source count."""
    header = (
        "## Thematic Synthesis Document\n"
        "Topic: Test Topic\n"
        "Generated by: Gemini Deep Research\n"
        f"Sources added beyond Source Validator: {sources_added}\n\n"
    )
    body = "\n\n".join(f"### {s}\nContent for {s}." for s in sections)
    return header + body


_ALL_SECTIONS = [
    "Synthesis Narrative",
    "Key Claims with Evidence",
    "Quantitative Gaps Identified",
    "Additional Sources Retrieved",
    "Thematic Threads for Analyst",
]

# ── 1. Valid document — all sections present ──────────────────────────────────


def test_valid_document_has_all_sections():
    """Valid fixture document returns has_all_sections=True."""
    result = parse_synthesis_document(_valid_doc())
    assert result["has_all_sections"] is True


def test_valid_document_missing_sections_empty():
    """Valid document produces an empty missing_sections list."""
    result = parse_synthesis_document(_valid_doc())
    assert result["missing_sections"] == []


def test_valid_document_sources_added_count():
    """Fixture document reports sources_added_count >= 1."""
    result = parse_synthesis_document(_valid_doc())
    assert result["sources_added_count"] >= 1


def test_valid_document_preserves_full_text():
    """full_text is the raw input unchanged."""
    raw = _valid_doc()
    result = parse_synthesis_document(raw)
    assert result["full_text"] == raw


# ── 2. Missing sections ───────────────────────────────────────────────────────


def test_missing_one_section_detected():
    """Document missing 'Thematic Threads for Analyst' is flagged."""
    sections = [s for s in _ALL_SECTIONS if s != "Thematic Threads for Analyst"]
    doc = _build_doc(sections)
    result = parse_synthesis_document(doc)
    assert result["has_all_sections"] is False
    assert "Thematic Threads for Analyst" in result["missing_sections"]


def test_missing_multiple_sections_all_listed():
    """All missing sections are listed, not just the first."""
    missing = ["Quantitative Gaps Identified", "Additional Sources Retrieved"]
    present = [s for s in _ALL_SECTIONS if s not in missing]
    doc = _build_doc(present)
    result = parse_synthesis_document(doc)
    assert result["has_all_sections"] is False
    for section in missing:
        assert section in result["missing_sections"]


def test_completely_empty_document_all_sections_missing():
    """Empty string produces has_all_sections=False with all 5 sections missing."""
    result = parse_synthesis_document("")
    assert result["has_all_sections"] is False
    assert len(result["missing_sections"]) == 5


# ── 3. sources_added_count extraction ────────────────────────────────────────


def test_sources_added_count_zero():
    """'Sources added beyond Source Validator: 0' is parsed as 0."""
    doc = _build_doc(_ALL_SECTIONS, sources_added=0)
    result = parse_synthesis_document(doc)
    assert result["sources_added_count"] == 0


def test_sources_added_count_nonzero():
    """'Sources added beyond Source Validator: 7' is parsed as 7."""
    doc = _build_doc(_ALL_SECTIONS, sources_added=7)
    result = parse_synthesis_document(doc)
    assert result["sources_added_count"] == 7


def test_sources_added_count_missing_line_defaults_to_zero():
    """If the sources-added line is absent, sources_added_count defaults to 0."""
    doc = _build_doc(_ALL_SECTIONS)
    # Strip the header line that contains the count
    doc_no_count = "\n".join(
        line for line in doc.splitlines()
        if "Sources added beyond Source Validator" not in line
    )
    result = parse_synthesis_document(doc_no_count)
    assert result["sources_added_count"] == 0


# ── 4. Malformed / truncated output fallback ──────────────────────────────────


def test_malformed_output_does_not_raise():
    """Garbage input never raises — parser always returns a dict."""
    garbage = "!@#$%^&*() \x00\x01 not a document"
    result = parse_synthesis_document(garbage)
    assert isinstance(result, dict)
    assert "has_all_sections" in result
    assert "missing_sections" in result
    assert "sources_added_count" in result
    assert "full_text" in result


def test_truncated_output_flagged_as_incomplete():
    """A document cut off mid-way has has_all_sections=False."""
    truncated = _valid_doc()[:300]
    result = parse_synthesis_document(truncated)
    # Truncated at 300 chars — unlikely to contain all 5 section headers
    assert isinstance(result["missing_sections"], list)


def test_non_integer_source_count_does_not_raise():
    """If the source count line is malformed, sources_added_count stays 0."""
    doc = (
        "## Thematic Synthesis Document\n"
        "Sources added beyond Source Validator: many\n\n"
        + "\n\n".join(f"### {s}\nContent." for s in _ALL_SECTIONS)
    )
    result = parse_synthesis_document(doc)
    assert result["sources_added_count"] == 0  # fallback on ValueError


# ── 5. Handoff data format ────────────────────────────────────────────────────


def test_handoff_dict_has_required_keys():
    """parse_synthesis_document output always contains the 4 handoff keys."""
    result = parse_synthesis_document(_valid_doc())
    assert set(result.keys()) >= {"full_text", "has_all_sections", "missing_sections", "sources_added_count"}


def test_handoff_types_are_correct():
    """Each handoff key has the expected Python type."""
    result = parse_synthesis_document(_valid_doc())
    assert isinstance(result["full_text"], str)
    assert isinstance(result["has_all_sections"], bool)
    assert isinstance(result["missing_sections"], list)
    assert isinstance(result["sources_added_count"], int)


def test_handoff_missing_sections_are_strings():
    """Each entry in missing_sections is a string (section name)."""
    doc = _build_doc(["Synthesis Narrative"])  # only 1 of 5 sections present
    result = parse_synthesis_document(doc)
    for item in result["missing_sections"]:
        assert isinstance(item, str)


def test_full_text_is_unchanged_for_downstream_analyst():
    """Macro Analyst receives the raw synthesis text unmodified (no truncation)."""
    raw = _valid_doc()
    result = parse_synthesis_document(raw)
    # The downstream analyst must receive the full, unmodified text
    assert result["full_text"] is raw or result["full_text"] == raw
    assert len(result["full_text"]) == len(raw)
