"""
tools/deep_research.py

Async client for the Gemini Deep Research API (Gemini Developer API).
Deep Research uses a separate API key (stored in Secret Manager as "google-ai-api-key")
rather than the Vertex AI service account auth used by all other agents.

Models:
  deep-research-preview-04-2026      — standard
  deep-research-max-preview-04-2026  — higher quality, slower

API ref: https://ai.google.dev/gemini-api/docs/deep-research
"""

import asyncio
import logging
import time

logger = logging.getLogger(__name__)

_DEEP_RESEARCH_MODEL = "deep-research-preview-04-2026"

_REQUIRED_SECTIONS = [
    "Synthesis Narrative",
    "Key Claims with Evidence",
    "Quantitative Gaps Identified",
    "Additional Sources Retrieved",
    "Thematic Threads for Analyst",
]


def _build_deep_research_prompt(
    topic: str,
    source_package: str,
    data_manifest: str,
    report_mode: str,
) -> str:
    """Build the research prompt sent to the Gemini Deep Research API."""
    mode_instruction = (
        "This synthesis will feed a report that includes both thematic analysis AND a potential "
        "trade recommendation. Pay particular attention to near-term catalysts, "
        "instrument-specific dynamics, and conviction-level evidence."
        if report_mode == "both"
        else "This synthesis will feed a purely thematic macro deep dive. "
             "Focus on structural forces, long-run dynamics, and policy implications."
    )

    return (
        f"You are conducting deep research for an institutional macro research pipeline.\n\n"
        f"TOPIC: {topic}\n\n"
        f"RESEARCH MODE: {report_mode}\n"
        f"{mode_instruction}\n\n"
        f"VALIDATED SOURCE PACKAGE (already gathered — do NOT re-fetch these sources):\n"
        f"{source_package}\n\n"
        f"QUANTITATIVE DATA MANIFEST (summary of pre-gathered structured data):\n"
        f"{data_manifest}\n\n"
        f"YOUR TASKS:\n"
        f"1. Synthesise the validated sources into a coherent thematic narrative.\n"
        f"2. Find additional sources NOT already in the validated package — prioritise:\n"
        f"   - Academic papers (BIS, IMF, NBER, CEPR, academic journals — on-geography, on-theme)\n"
        f"   - Central bank speeches and working papers matching the topic's primary geography\n"
        f"   - BIS, IMF, and OECD working papers (last 3 years)\n"
        f"   - Historical analog literature for the identified theme\n"
        f"3. Identify quantitative data referenced in sources but absent from the data manifest.\n\n"
        f"Return your output in EXACTLY this format:\n\n"
        f"## Thematic Synthesis Document\n"
        f"Topic: {topic}\n"
        f"Generated by: Gemini Deep Research\n"
        f"Sources added beyond Source Validator: [N]\n\n"
        f"### Synthesis Narrative\n"
        f"[2-4 paragraphs: thematic framing, key tensions, structural forces, consensus/dissent]\n\n"
        f"### Key Claims with Evidence\n"
        f"[Bullet list: claim (Source, Year) — HIGH/MEDIUM/LOW CONFIDENCE]\n\n"
        f"### Quantitative Gaps Identified\n"
        f"[Bullet list or 'None identified.']\n\n"
        f"### Additional Sources Retrieved\n"
        f"| # | Title | Source | Date | URL |\n"
        f"|---|---|---|---|---|\n"
        f"[One row per new source]\n\n"
        f"### Thematic Threads for Analyst\n"
        f"[3-5 threads: 'Thread N: Title — one sentence description']"
    )


def parse_synthesis_document(raw: str) -> dict:
    """
    Parse the Deep Research output into a structured dict.

    Returns:
        full_text: str — raw output unchanged
        has_all_sections: bool — True if all 5 required sections present
        missing_sections: list[str] — names of any missing sections
        sources_added_count: int — additional sources retrieved
    """
    result = {
        "full_text": raw,
        "has_all_sections": True,
        "missing_sections": [],
        "sources_added_count": 0,
    }
    for section in _REQUIRED_SECTIONS:
        if f"### {section}" not in raw and f"## {section}" not in raw:
            result["has_all_sections"] = False
            result["missing_sections"].append(section)
    for line in raw.splitlines():
        if "Sources added beyond Source Validator:" in line:
            try:
                result["sources_added_count"] = int(line.split(":")[-1].strip().split()[0])
            except (ValueError, IndexError):
                pass
    return result


_POLL_INTERVAL = 15  # seconds between status checks


async def run_deep_research(
    topic: str,
    source_package: str,
    data_manifest: str,
    report_mode: str = "research",
    api_key: str = None,
    timeout: int = 600,
) -> str:
    """
    Call the Gemini Deep Research API and return the synthesis text.

    Uses the Interactions API (client.interactions.create) — the only API surface
    supported by Deep Research models. The standard generate_content endpoint
    returns 400 INVALID_ARGUMENT for these models.

    The interaction is submitted with background=True and polled every
    _POLL_INTERVAL seconds until completed or timeout is reached.

    On timeout or API error, raises an exception — callers catch and fall back
    to source_package as the Macro Analyst's primary qualitative input.

    Args:
        topic: Macro research topic string.
        source_package: Source Validator output (full text).
        data_manifest: Compact macro data manifest (~400 words).
        report_mode: "research" or "both".
        api_key: Gemini Developer API key. Loaded from Secret Manager if None.
        timeout: Max seconds to wait for completion (default 600s).
    """
    try:
        from google import genai
    except ImportError as exc:
        raise ImportError(
            "google-genai is required for Deep Research. "
            "Ensure it is listed in requirements.txt and redeploy."
        ) from exc

    if not api_key:
        import os
        api_key = (
            os.environ.get("GOOGLE_AI_API_KEY")
            or os.environ.get("GOOGLE_API_KEY")
            or os.environ.get("GEMINI_API_KEY")
        )
        if not api_key:
            raise ValueError(
                "No Gemini API key found. Set GOOGLE_AI_API_KEY env var or ensure "
                "'google-ai-api-key' is accessible from Secret Manager."
            )

    # vertexai=False overrides the GOOGLE_GENAI_USE_VERTEXAI=1 env var set globally
    # for all other agents. Deep Research is only on the Gemini Developer API —
    # it returns 404 NOT_FOUND when routed through Vertex AI.
    client = genai.Client(api_key=api_key, vertexai=False)
    prompt = _build_deep_research_prompt(topic, source_package, data_manifest, report_mode)
    logger.info("Deep Research: submitting for topic='%s' mode='%s'", topic, report_mode)
    start = time.monotonic()

    def _submit():
        """Submit the background interaction and return the interaction ID."""
        interaction = client.interactions.create(
            input=prompt,
            agent=_DEEP_RESEARCH_MODEL,
            background=True,
        )
        return interaction.id

    def _poll(interaction_id: str) -> str:
        """
        Poll until the interaction completes, fails, or the deadline passes.
        Returns the synthesis text on success.
        """
        deadline = start + timeout
        while True:
            interaction = client.interactions.get(interaction_id)
            status = interaction.status
            elapsed = time.monotonic() - start
            logger.info(
                "Deep Research: id=%s status=%s elapsed=%.0fs",
                interaction_id, status, elapsed,
            )

            if status == "completed":
                if not interaction.outputs:
                    raise ValueError(
                        f"Deep Research interaction {interaction_id} completed with no outputs"
                    )
                return interaction.outputs[-1].text

            if status in ("failed", "cancelled", "error"):
                raise RuntimeError(
                    f"Deep Research interaction {interaction_id} ended with status={status}"
                )

            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise TimeoutError(
                    f"Deep Research timed out after {elapsed:.0f}s for topic='{topic}'"
                )
            time.sleep(min(_POLL_INTERVAL, remaining))

    loop = asyncio.get_event_loop()
    interaction_id = await loop.run_in_executor(None, _submit)
    logger.info("Deep Research: submitted interaction_id=%s", interaction_id)

    try:
        result = await asyncio.wait_for(
            loop.run_in_executor(None, _poll, interaction_id),
            timeout=timeout,
        )
    except asyncio.TimeoutError:
        raise TimeoutError(
            f"Deep Research timed out after {time.monotonic() - start:.0f}s for topic='{topic}'"
        )

    logger.info("Deep Research: done in %.0fs, %d chars", time.monotonic() - start, len(result))
    return result
